(function () {
  "use strict";

  window.__BRAND__ = {
    name: "IncluJob",
    tagline: "Tu talento no tiene límites",
    email: "hola@inclujob.es",
    phone: "+34 900 123 456",

    stats: { ofertas: 12, empresas: 0, personas: 0 },

    jobs: [
      {
        id: "j-001",
        title: "Técnico/a de Soporte IT",
        company: "Telefónica",
        initials: "TF",
        color: "#0066cc",
        city: "Madrid",
        modality: "híbrido",
        contract: "Indefinido",
        sector: "tecnología",
        date: "2026-05-17",
        disabilities: ["física", "auditiva"],
        salary: "22.000 – 26.000 €/año",
        description: "Buscamos Técnico/a de Soporte IT con certificado de discapacidad igual o superior al 33%. Darás soporte técnico a usuarios internos, gestionarás incidencias y colaborarás con el equipo de sistemas. Horario flexible y teletrabajo 3 días por semana. Se valorará formación en informática o ciclo FP relacionado.",
        requirements: ["Ciclo FP Informática o similar", "Conocimientos de Windows, Office, redes básicas", "Certificado de discapacidad ≥33%", "Buena comunicación"],
        benefits: ["Teletrabajo 3 días/semana", "Seguro médico", "Formación continua", "Flex time"]
      },
      {
        id: "j-002",
        title: "Auxiliar Administrativo/a",
        company: "BBVA",
        initials: "BB",
        color: "#004a97",
        city: "Barcelona",
        modality: "presencial",
        contract: "Indefinido",
        sector: "administración",
        date: "2026-05-16",
        disabilities: ["física", "visual", "auditiva"],
        salary: "19.000 – 22.000 €/año",
        description: "El Banco BBVA incorpora Auxiliar Administrativo/a para su red de oficinas en Barcelona. Gestión de documentación, atención al cliente y apoyo a operaciones bancarias. Entorno adaptado y equipo comprometido con la inclusión.",
        requirements: ["Estudios de administración o similares", "Manejo de Excel y herramientas Office", "Orientación al cliente"],
        benefits: ["Jornada completa", "Plan de pensiones", "Descuentos bancarios", "Formación interna"]
      },
      {
        id: "j-003",
        title: "Desarrollador/a Web Frontend",
        company: "Indra",
        initials: "IN",
        color: "#e30016",
        city: "Remoto",
        modality: "remoto",
        contract: "Indefinido",
        sector: "tecnología",
        date: "2026-05-15",
        disabilities: ["física", "visual", "intelectual"],
        salary: "28.000 – 36.000 €/año",
        description: "Indra busca Desarrollador/a Frontend para proyecto internacional. Trabajarás con React, TypeScript y diseño de componentes accesibles (WCAG 2.1). 100% remoto con equipo distribuido. Buscamos personas apasionadas por la tecnología inclusiva.",
        requirements: ["React + TypeScript (2+ años)", "Conocimientos de accesibilidad web (WCAG)", "Git y metodologías ágiles"],
        benefits: ["100% remoto", "Horario flexible", "27 días de vacaciones", "Equipo proporcionado"]
      },
      {
        id: "j-004",
        title: "Agente de Atención al Cliente",
        company: "Amazon",
        initials: "AM",
        color: "#ff9900",
        city: "Madrid",
        modality: "híbrido",
        contract: "Temporal",
        sector: "atención al cliente",
        date: "2026-05-14",
        disabilities: ["física", "auditiva", "múltiple"],
        salary: "17.000 – 19.000 €/año",
        description: "Amazon España necesita Agentes de Atención al Cliente para reforzar su equipo. Resolución de consultas por chat y email, gestión de pedidos y devoluciones. Formación a cargo de la empresa. Compatible con trabajo desde casa 2 días/semana.",
        requirements: ["Buena expresión escrita en español", "Habilidades de comunicación", "Conocimientos básicos de informática"],
        benefits: ["Formación inicial remunerada", "Descuentos Amazon", "Transporte cubierto", "Posibilidad de indefinido"]
      },
      {
        id: "j-005",
        title: "Diseñador/a Gráfico/a",
        company: "Havas Creative",
        initials: "HC",
        color: "#6d2a7a",
        city: "Barcelona",
        modality: "híbrido",
        contract: "Indefinido",
        sector: "tecnología",
        date: "2026-05-13",
        disabilities: ["física", "auditiva"],
        salary: "23.000 – 29.000 €/año",
        description: "Agencia creativa Havas busca Diseñador/a Gráfico/a con ganas de aportar su visión única. Diseño de campañas, piezas digitales y materiales de branding para clientes nacionales e internacionales. Estudio completamente adaptado.",
        requirements: ["Dominio de Adobe Creative Suite", "Portfolio creativo", "Inglés nivel medio"],
        benefits: ["Viernes tarde libre", "Eventos de equipo", "Material creativo cubierto", "Mentoring"]
      },
      {
        id: "j-006",
        title: "Operario/a de Almacén",
        company: "Mercadona",
        initials: "MC",
        color: "#009a44",
        city: "Valencia",
        modality: "presencial",
        contract: "Indefinido",
        sector: "logística",
        date: "2026-05-12",
        disabilities: ["auditiva", "intelectual"],
        salary: "18.500 – 21.000 €/año",
        description: "Mercadona incorpora Operarios/as de Almacén en sus instalaciones logísticas de Valencia. Recepción, clasificación y preparación de pedidos. Entorno de trabajo adaptado, ritmo progresivo y equipo de apoyo permanente.",
        requirements: ["Disponibilidad horaria", "Trabajo en equipo", "Dinamismo y responsabilidad"],
        benefits: ["Plus de productividad", "Comedor subvencionado", "Transporte de empresa", "Plan de carrera"]
      },
      {
        id: "j-007",
        title: "Community Manager",
        company: "Social Now",
        initials: "SN",
        color: "#1da1f2",
        city: "Remoto",
        modality: "remoto",
        contract: "Temporal",
        sector: "comunicación",
        date: "2026-05-11",
        disabilities: ["física", "visual", "múltiple"],
        salary: "16.000 – 20.000 €/año",
        description: "Startup de comunicación digital busca Community Manager apasionado/a por las redes sociales. Gestión de cuentas de clientes, creación de contenido, análisis de métricas y estrategia de engagement. 100% teletrabajo.",
        requirements: ["Experiencia en RRSS (1+ año)", "Creatividad y escritura", "Conocimientos de analytics básico"],
        benefits: ["100% remoto", "Horario flexible", "Formación continua", "Posibilidad de indefinido"]
      },
      {
        id: "j-008",
        title: "Recepcionista de Hotel",
        company: "NH Collection",
        initials: "NH",
        color: "#c8902a",
        city: "Sevilla",
        modality: "presencial",
        contract: "Indefinido",
        sector: "hostelería",
        date: "2026-05-10",
        disabilities: ["física", "auditiva"],
        salary: "18.000 – 21.000 €/año",
        description: "NH Collection busca Recepcionista para sus hoteles en Sevilla. Check-in/check-out, atención personalizada al huésped, gestión de reservas y coordinación con otros departamentos. Uniforme y comidas durante el turno incluidos.",
        requirements: ["Inglés nivel B2 o superior", "Actitud amable y profesional", "Disponibilidad de turnos"],
        benefits: ["Noches de hotel a precio empleado", "Descuentos Minor Hotels", "Formación en idiomas"]
      },
      {
        id: "j-009",
        title: "Analista de Datos",
        company: "Deloitte",
        initials: "DL",
        color: "#86bc25",
        city: "Madrid",
        modality: "híbrido",
        contract: "Indefinido",
        sector: "tecnología",
        date: "2026-05-09",
        disabilities: ["física", "visual"],
        salary: "32.000 – 42.000 €/año",
        description: "Deloitte incorpora Analista de Datos para su práctica Analytics. Trabajarás con Power BI, Python y SQL para generar insights de negocio para clientes del Fortune 500. Ambiente inclusivo y equipos de alto rendimiento.",
        requirements: ["Grado en estadística, matemáticas o similar", "Python o R", "SQL intermedio", "Power BI o Tableau"],
        benefits: ["Bonus anual", "Seguro médico premium", "Formación certificada", "Teletrabajo flexible"]
      },
      {
        id: "j-010",
        title: "Auxiliar de Biblioteca",
        company: "Comunidad de Madrid",
        initials: "CM",
        color: "#c01818",
        city: "Madrid",
        modality: "presencial",
        contract: "Temporal",
        sector: "administración",
        date: "2026-05-08",
        disabilities: ["física", "auditiva", "intelectual"],
        salary: "16.500 – 18.000 €/año",
        description: "La Comunidad de Madrid convoca plazas de Auxiliar de Biblioteca con reserva de cupo para personas con discapacidad. Atención a usuarios, gestión de fondos documentales, préstamos y actividades culturales.",
        requirements: ["Bachillerato o equivalente", "Conocimientos de catalogación", "Interés por la cultura"],
        benefits: ["Estabilidad laboral", "Jornada continua", "Acceso a formación pública", "Conciliación familiar"]
      },
      {
        id: "j-011",
        title: "Técnico/a de RR.HH.",
        company: "Inditex",
        initials: "IT",
        color: "#212121",
        city: "A Coruña",
        modality: "híbrido",
        contract: "Indefinido",
        sector: "administración",
        date: "2026-05-07",
        disabilities: ["física", "auditiva"],
        salary: "24.000 – 29.000 €/año",
        description: "Inditex busca Técnico/a de Recursos Humanos para reforzar su equipo de People en sede central. Selección, onboarding, gestión de beneficios y proyectos de diversidad e inclusión. Empresa líder comprometida con la igualdad.",
        requirements: ["Grado en RRHH, Psicología o ADE", "Conocimiento de legislación laboral", "Excel avanzado"],
        benefits: ["Descuento empleado 25%", "2 días teletrabajo/semana", "Plan de carrera", "Seguro médico"]
      },
      {
        id: "j-012",
        title: "Técnico/a de Mantenimiento",
        company: "RENFE",
        initials: "RF",
        color: "#e10015",
        city: "Valencia",
        modality: "presencial",
        contract: "Indefinido",
        sector: "logística",
        date: "2026-05-06",
        disabilities: ["auditiva", "intelectual"],
        salary: "21.000 – 25.000 €/año",
        description: "RENFE Viajeros incorpora Técnicos/as de Mantenimiento en sus talleres de Valencia. Revisión, reparación y mantenimiento preventivo de material rodante. Equipo experimentado, formación técnica completa y ambiente seguro.",
        requirements: ["FP Mecatrónica o electromecánica", "Disponibilidad de turnos", "Trabajo en equipo"],
        benefits: ["Pase de libre circulación", "Complemento nocturnidad", "Formación técnica pagada"]
      }
    ],

    companies: [
      { name: "Telefónica", badge: "TF", color: "#0066cc", jobs: 8 },
      { name: "BBVA", badge: "BB", color: "#004a97", jobs: 6 },
      { name: "Amazon", badge: "AM", color: "#ff9900", jobs: 12 },
      { name: "Mercadona", badge: "MC", color: "#009a44", jobs: 4 },
      { name: "Deloitte", badge: "DL", color: "#86bc25", jobs: 9 },
      { name: "RENFE", badge: "RF", color: "#e10015", jobs: 3 },
      { name: "Inditex", badge: "IT", color: "#212121", jobs: 7 },
      { name: "NH Hotels", badge: "NH", color: "#c8902a", jobs: 5 },
      { name: "Indra", badge: "IN", color: "#e30016", jobs: 11 },
      { name: "El Corte Inglés", badge: "ECI", color: "#006400", jobs: 14 },
      { name: "Mapfre", badge: "MF", color: "#c62828", jobs: 6 },
      { name: "Acciona", badge: "AC", color: "#00a651", jobs: 8 }
    ],

    // Proyecto Supabase de Incloo (pcvfwlbefnwwexhaenph).
    // "key" debe ser la clave pública del proyecto (anon / publishable):
    // Dashboard → Project Settings → API Keys → anon public / publishable.
    // Es el ÚNICO sitio donde hay que pegarla — el resto de la web la lee de aquí.
    supabase: {
      url: "https://pcvfwlbefnwwexhaenph.supabase.co",
      key: ""
    },

    cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Málaga", "Murcia", "Palma", "Bilbao", "Alicante", "Valladolid", "Remoto"],
    disabilities: ["física", "visual", "auditiva", "intelectual", "múltiple"],
    sectors: ["tecnología", "administración", "atención al cliente", "logística", "hostelería", "comunicación"]
  };
})();
